openapi: 3.1.0
info:
  title: Auth Service API
  version: 1.0.0
  description: API для проверки аккаунтов и проектов в системе аутентификации

servers:
  - url: https://api.auth-service.example.com/v1
    description: Production server

paths:
  /accounts:
    get:
      tags:
        - Accounts
      summary: Получение информации об аккаунте по email
      description: Проверка существования пользователя с указанным email
      operationId: getAccountByEmail
      parameters:
        - name: email
          in: query
          required: true
          schema:
            type: string
            format: email
          description: Email адрес для поиска аккаунта
      responses:
        '200':
          description: Информация об аккаунте
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '404':
          description: Аккаунт не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: Неверный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /projects/{projectId}/ownership:
    get:
      tags:
        - Projects
      summary: Проверка принадлежности проекта аккаунту
      description: Проверяет, принадлежит ли указанный проект аккаунту с данным email
      operationId: checkProjectOwnership
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: ID проекта
        - name: email
          in: query
          required: true
          schema:
            type: string
            format: email
          description: Email адрес аккаунта для проверки владения
      responses:
        '200':
          description: Результат проверки владения проектом
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectOwnership'
        '403':
          description: Доступ запрещен (проект не принадлежит аккаунту)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Проект или аккаунт не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: Неверный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Account:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Уникальный идентификатор аккаунта
        email:
          type: string
          format: email
          description: Email адрес аккаунта
        createdAt:
          type: string
          format: date-time
          description: Дата создания аккаунта
        accountType:
          type: string
          enum: [user, project]
          description: Тип аккаунта
      required:
        - id
        - email
        - createdAt
        - accountType

    ProjectOwnership:
      type: object
      properties:
        isOwner:
          type: boolean
          description: Флаг, указывающий является ли аккаунт владельцем проекта
        projectId:
          type: string
          format: uuid
          description: ID проекта
        accountId:
          type: string
          format: uuid
          description: ID аккаунта
      required:
        - isOwner
        - projectId
        - accountId

    Error:
      type: object
      properties:
        error:
          type: string
          description: Код ошибки
        message:
          type: string
          description: Описание ошибки
      required:
        - error
        - message