swagger: "2.0"
info:
  title: Auth Service API
  version: 1.0.0
  description: API для проверки аккаунтов и проектов в системе аутентификации

#host: api.auth-service.example.com
basePath: /v1
schemes:
  - https

paths:
  /accounts:
    get:
      tags:
        - Accounts
      summary: Получение информации об аккаунте по email
      description: Проверка существования пользователя с указанным email
      operationId: getAccountByEmail
      parameters:
        - name: email
          in: query
          required: true
          type: string
          format: email
          description: Email адрес для поиска аккаунта
      responses:
        "200":
          description: Информация об аккаунте
          schema:
            $ref: "#/definitions/Account"
        "404":
          description: Аккаунт не найден
          schema:
            $ref: "#/definitions/Error"
        "400":
          description: Неверный запрос
          schema:
            $ref: "#/definitions/Error"

  /projects/{projectId}/ownership:
    get:
      tags:
        - Projects
      summary: Проверка принадлежности проекта аккаунту
      description: Проверяет, принадлежит ли указанный проект аккаунту с данным email
      operationId: checkProjectOwnership
      parameters:
        - name: projectId
          in: path
          required: true
          type: string
          format: uuid
          description: ID проекта
        - name: email
          in: query
          required: true
          type: string
          format: email
          description: Email адрес аккаунта для проверки владения
      responses:
        "200":
          description: Результат проверки владения проектом
          schema:
            $ref: "#/definitions/ProjectOwnership"
        "403":
          description: Доступ запрещен (проект не принадлежит аккаунту)
          schema:
            $ref: "#/definitions/Error"
        "404":
          description: Проект или аккаунт не найден
          schema:
            $ref: "#/definitions/Error"
        "400":
          description: Неверный запрос
          schema:
            $ref: "#/definitions/Error"

definitions:
  Account:
    type: object
    properties:
      id:
        type: string
        format: uuid
        description: Уникальный идентификатор аккаунта
      email:
        type: string
        format: email
        description: Email адрес аккаунта
      createdAt:
        type: string
        format: date-time
        description: Дата создания аккаунта
      accountType:
        type: string
        enum:
          - user
          - project
        description: Тип аккаунта
    required:
      - id
      - email
      - createdAt
      - accountType

  ProjectOwnership:
    type: object
    properties:
      isOwner:
        type: boolean
        description: Флаг, указывающий является ли аккаунт владельцем проекта
      projectId:
        type: string
        format: uuid
        description: ID проекта
      accountId:
        type: string
        format: uuid
        description: ID аккаунта
    required:
      - isOwner
      - projectId
      - accountId

  Error:
    type: object
    properties:
      error:
        type: string
        description: Код ошибки
      message:
        type: string
        description: Описание ошибки
    required:
      - error
      - message